# Generated by Django 4.1.13 on 2024-06-21 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('athlete_url', models.CharField(max_length=255)),
                ('athlete_full_name', models.CharField(max_length=255)),
                ('games_participations', models.IntegerField()),
                ('first_game', models.CharField(max_length=100)),
                ('athlete_year_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_slug', models.CharField(max_length=100)),
                ('game_end_date', models.DateTimeField()),
                ('game_start_date', models.DateTimeField()),
                ('game_location', models.CharField(max_length=255)),
                ('game_name', models.CharField(max_length=255)),
                ('game_season', models.CharField(max_length=100)),
                ('game_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline_title', models.CharField(max_length=255)),
                ('slug_game', models.CharField(max_length=100)),
                ('event_title', models.CharField(max_length=255)),
                ('event_gender', models.CharField(max_length=10)),
                ('medal_type', models.CharField(max_length=50)),
                ('participant_type', models.CharField(max_length=50)),
                ('participant_title', models.CharField(max_length=255)),
                ('athlete_url', models.CharField(max_length=255)),
                ('athlete_full_name', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('country_3_letter_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline_title', models.CharField(max_length=255)),
                ('event_title', models.CharField(max_length=255)),
                ('slug_game', models.CharField(max_length=100)),
                ('participant_type', models.CharField(max_length=50)),
                ('medal_type', models.CharField(max_length=50)),
                ('athletes', models.TextField()),
                ('rank_equal', models.BooleanField()),
                ('rank_position', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('country_3_letter_code', models.CharField(max_length=3)),
            ],
        ),
    ]
