# Generated by Django 4.1.13 on 2024-06-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_url', models.URLField(max_length=500)),
                ('athlete_full_name', models.CharField(max_length=255)),
                ('games_participations', models.IntegerField()),
                ('first_game', models.CharField(max_length=255)),
                ('athlete_year_birth', models.CharField(max_length=10)),
                ('athlete_medals', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(max_length=255)),
                ('game_end_date', models.DateTimeField()),
                ('game_start_date', models.DateTimeField()),
                ('game_location', models.CharField(max_length=255)),
                ('game_name', models.CharField(max_length=255)),
                ('game_season', models.CharField(max_length=50)),
                ('game_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_title', models.CharField(max_length=255)),
                ('slug_game', models.CharField(max_length=255)),
                ('event_title', models.CharField(max_length=255)),
                ('event_gender', models.CharField(max_length=50)),
                ('medal_type', models.CharField(max_length=50)),
                ('participant_type', models.CharField(max_length=50)),
                ('participant_title', models.CharField(max_length=255)),
                ('athlete_url', models.URLField(max_length=500)),
                ('athlete_full_name', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('country_3_letter_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_title', models.CharField(max_length=255)),
                ('event_title', models.CharField(max_length=255)),
                ('slug_game', models.CharField(max_length=100)),
                ('participant_type', models.CharField(max_length=50)),
                ('medal_type', models.CharField(blank=True, max_length=10, null=True)),
                ('athletes', models.TextField()),
                ('rank_equal', models.BooleanField()),
                ('rank_position', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('country_3_letter_code', models.CharField(max_length=3)),
                ('athlete_url', models.URLField(blank=True, null=True)),
                ('athlete_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('value_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('value_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
